vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        series:
            uri_prefix: /img/series
            upload_destination: '%kernel.project_dir%/public/img/series'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
